coverage:
  range: 50..80 # test coverage thresholds. 50% and below fails (red), 80% and up passes (green), between is "yellow"
  round: down
  precision: 1
  status:
    patch:
      default:
        enabled: no
