name: Master Build

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Install Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
      
    - name: Dotnet Installation Info
      run: dotnet --info
      
    - name: Install Codecov
      run: dotnet tool install --global Codecov.Tool
      
    - name: Build
      run: dotnet build
      
    - name: Test
      run: dotnet test --collect:"XPlat Code Coverage" --settings Replay.Tests\TestCoverageRunSettings.xml

    - name: Code Coverage
      shell: pwsh
      run: |
        $testCoverage = Get-ChildItem Replay.Tests\TestResults\*\*.xml
        codecov -t ${{ secrets.CODECOV_TOKEN }} -f $testCoverage[0].ToString()
